# Generated by Django 5.1.3 on 2024-12-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scienceissue_rename_viewer_count_section_views_and_more'),
    ]

    operations = [
    ]
